# Generated by Django 6.0 on 2025-12-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_more_faqs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
