# Generated by Django 6.0 on 2025-12-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_user_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created',), 'verbose_name': 'Customer Review', 'verbose_name_plural': 'Customer Reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Optional avatar image URL', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
