# Generated by Django 5.2.8 on 2025-12-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_address_order_city_order_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starters', 'Starters'), ('main_course', 'Main Course'), ('biryani', 'Biryani'), ('breads', 'Breads'), ('rice', 'Rice & Noodles'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('desserts', 'Desserts')], default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
